---
- name: Add NodeSource repository (Node.js 16)
  raw: curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
  args:
    warn: false
  tags: nodejs

- name: Install Node.js
  raw: yum install -y nodejs
  tags: nodejs

- name: Verify Node.js installation
  command: node --version
  register: node_version
  changed_when: false
  tags: nodejs

- debug:
    msg: "Node.js version installed: {{ node_version.stdout }}"
