---
- name: Install PM2 globally
  command: npm install -g pm2
  become: yes
  environment:
    PATH: /usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin


- name: Generate PM2 startup systemd unit
  command: >
    pm2 startup systemd
    -u {{ frontend_user }}
    --hp /home/{{ frontend_user }}
  become: yes
  environment:
    PATH: /usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin
  args:
    creates: /etc/systemd/system/pm2-{{ frontend_user }}.service


- name: Enable PM2 service
  systemd:
    name: pm2-{{ frontend_user }}
    enabled: yes
    daemon_reload: yes
  become: yes