# QA Environment Inventory
# Backend instances in private subnets
# Executed FROM Bastion Host

[backend]
backend-1 ansible_host=10.0.11.71
backend-2 ansible_host=10.0.12.244

[backend:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/movie-analyst-bastion-key
ansible_python_interpreter=/usr/bin/python3