---
# ansible/roles/frontend/handlers/main.yml

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: true

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: true

- name: restart pm2
  command: pm2 restart all
  become: true
  become_user: "{{ app_user }}"
  ignore_errors: true