---
- name: restart pm2 app
  command: pm2 reload {{ pm2_app_name }}
  become_user: "{{ frontend_user }}"
  ignore_errors: yes


- name: validate and reload nginx
  block:
    - name: Validate nginx configuration
      command: nginx -t
      become: yes

    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded
  become: yes
